server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091
logging:
  level: INFO
  loggers:
    com.hubspot.testapi: DEBUG
hubspotApi:
  url: https://candidate.hubteam.com
swagger:
  resourcePackage: com.hubspot.testapi.resources
  title: SchedulerAPI
  version: 1.0-SNAPSHOT
  description:
  contact: vedang91@gmail.com
